# Generated by Django 4.1.2 on 2023-06-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('descricao', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('modalidade', models.CharField(max_length=15)),
                ('local', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=20)),
                ('max_volunt', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('senha', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('telefone1', models.CharField(max_length=11)),
                ('telefone2', models.CharField(max_length=11)),
                ('cidade', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=15)),
                ('data_nasc', models.DateTimeField(verbose_name='data de nascimento')),
                ('bio', models.TextField()),
                ('incrito_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ManyToManyField(to='base.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.proprietario')),
                ('voluntario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proprietario',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usuario'),
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='None')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.acao')),
            ],
        ),
        migrations.AddField(
            model_name='acao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categoria'),
        ),
    ]
