# Generated by Django 4.2 on 2023-06-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=6)),
                ('cidade', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=15)),
                ('referencia', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('dia_semana', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('senha', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=11)),
                ('cidade', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=15)),
                ('data_nasc', models.DateTimeField(verbose_name='data de nascimento')),
                ('biografia', models.TextField()),
                ('incrito_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('descricao_acao', models.TextField()),
                ('criada_em', models.DateField(auto_now_add=True)),
                ('modalidade', models.CharField(max_length=10)),
                ('tema', models.CharField(max_length=10)),
                ('num_max_voluntario', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categoria')),
                ('ocorrencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.periodo')),
            ],
        ),
    ]
