# Generated by Django 4.1.2 on 2023-07-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_proprietario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('ESP', 'Em espera'), ('ACC', 'Aceito'), ('REJ', 'Rejeitado'), ('PART', 'Participou')], default='ESP', max_length=4),
        ),
    ]
