# Generated by Django 4.2 on 2023-07-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='acao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.acao'),
        ),
    ]
