# Generated by Django 4.2 on 2023-07-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='acao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.acao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='base.categoria'),
        ),
    ]
