# Generated by Django 4.1.2 on 2023-07-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_proprietario_acao_alter_usuario_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='incrito_em',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AddField(
            model_name='acao',
            name='avaliacao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='max_volunt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='modalidade',
            field=models.BooleanField(),
        ),
    ]
