# Generated by Django 4.1.2 on 2023-07-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_usuario_email_remove_usuario_incrito_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.usuario'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
    ]
