# Generated by Django 4.1.2 on 2023-07-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_alter_foto_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="foto",
            field=models.ImageField(null=True, upload_to="settings.MEDIA_URL"),
        ),
    ]
