# Generated by Django 4.1.2 on 2023-07-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(null=True, upload_to='media/imagensacoes'),
        ),
    ]
