# Generated by Django 4.1.2 on 2023-07-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='voluntario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.usuario'),
        ),
    ]
