version: "3.9"
services:
  django:
    container_name: qajuda-api
    image: qajuda/backend-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - imagens-api:/qajuda-api/app/backend/APIQAjuda/static/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./compose/.env

  postgres:
    container_name: qajuda-db
    image: postgres:16
    env_file:
      - ./compose/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  imagens-api:
  postgres-data: