version: "3.8"

services:
  django:
    container_name: qajuda-api
    image: qajuda/backend:azure
    build:
      context: .
    volumes:
      - imagens-api:/qajuda-api/app/backend/APIQAjuda/static/
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: qajuda
      POSTGRES_PASSWORD: qajuda-password
      POSTGRES_DB: qajudadb
      POSTGRES_HOST: qajuda-db
      POSTGRES_PORT: 5432
    networks:
      - qajuda-network

volumes:
  imagens-api:

networks:
  qajuda-network:
    external: true
