# Generated by Django 4.2.6 on 2023-10-09 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('modalidade', models.BooleanField()),
                ('local', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=20)),
                ('max_volunt', models.IntegerField(null=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(null=True)),
                ('avaliacao', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone1', models.CharField(max_length=11)),
                ('telefone2', models.CharField(max_length=11)),
                ('cidade', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=15)),
                ('data_nasc', models.DateTimeField(verbose_name='data de nascimento')),
                ('bio', models.TextField()),
                ('categoria', models.ManyToManyField(blank=True, to='APIQAjuda.categoria')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.colaborador')),
                ('acao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.acao')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ESP', 'Em espera'), ('ACC', 'Aceito'), ('REJ', 'Rejeitado'), ('PART', 'Participou')], default='ESP', max_length=4)),
                ('Responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIQAjuda.responsavel')),
                ('acao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.acao')),
                ('voluntario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='media/imagensacoes')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.acao')),
            ],
        ),
        migrations.AddField(
            model_name='acao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIQAjuda.categoria'),
        ),
        migrations.AddField(
            model_name='acao',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.colaborador'),
        ),
    ]
