# Generated by Django 4.2.6 on 2023-10-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0003_colaborador_acao_notificacao_preferencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name_plural': 'Ações'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='colaborador_acao',
            options={'verbose_name_plural': 'Colaboradores_acões'},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterModelOptions(
            name='preferencia',
            options={'verbose_name_plural': 'Preferências'},
        ),
        migrations.AlterField(
            model_name='acao',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIQAjuda.colaborador'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='max_volunt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='tema',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='APIQAjuda.categoria'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador_acao',
            name='convite',
            field=models.CharField(blank=True, choices=[('ESP', 'Em espera'), ('ACC', 'Aceito'), ('REJ', 'Rejeitado'), ('PART', 'Participou')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador_acao',
            name='criador',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador_acao',
            name='data_responsavel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador_acao',
            name='data_solicitacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador_acao',
            name='responsavel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador_acao',
            name='solicitacao',
            field=models.CharField(blank=True, choices=[('ESP', 'Em espera'), ('ACC', 'Aceito'), ('REJ', 'Rejeitado'), ('PART', 'Participou')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagensacoes'),
        ),
    ]
