# Generated by Django 4.2.6 on 2023-10-25 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0004_alter_acao_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.categoria'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='criador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.colaborador'),
        ),
    ]
