# Generated by Django 4.2.6 on 2023-10-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0008_alter_colaborador_acao_convite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador_acao',
            name='criador',
        ),
        migrations.AlterField(
            model_name='acao',
            name='criador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.colaborador'),
        ),
    ]
