# Generated by Django 4.2.6 on 2023-12-14 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0015_alter_acao_foto_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.foto'),
        ),
    ]
