# Generated by Django 4.2.6 on 2023-12-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0016_alter_acao_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
