# Generated by Django 4.2.6 on 2023-12-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0017_alter_foto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, default=1, null=True, upload_to='media'),
        ),
    ]
