# Generated by Django 4.2.6 on 2023-12-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0018_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(default='teste.png', upload_to='media'),
        ),
    ]
