# Generated by Django 4.2.6 on 2023-12-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0020_alter_acao_foto_alter_foto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='criador',
        ),
        migrations.AlterField(
            model_name='acao',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.foto'),
        ),
        migrations.AddField(
            model_name='acao',
            name='criador',
            field=models.ManyToManyField(to='APIQAjuda.colaborador'),
        ),
    ]
