# Generated by Django 4.2.6 on 2024-03-04 12:59
from django.db import models

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0025_alter_acao_criador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='data_nasc',
            new_name='data_nascimento',
        ),
    ]
