# Generated by Django 4.2.6 on 2024-03-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0027_rename_colaborador_acao_colaboradoracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('E', 'Em espera'), ('A', 'Aceito'), ('R', 'Rejeitado'), ('P', 'Participou')], max_length=1, null=True)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.acao')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.colaborador')),
            ],
            options={
                'verbose_name_plural': 'Solicitações de Voluntariado',
            },
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='colaborador_acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.solicitacaovoluntariado'),
        ),
        migrations.DeleteModel(
            name='ColaboradorAcao',
        ),
    ]
