# Generated by Django 4.2.6 on 2024-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0028_solicitacaovoluntariado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='modalidade',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='APIQAjuda/static/'),
        ),
    ]
