name: Build and deploy images to Docker Hub
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api backend to dockerhub
        run: |
          docker compose -f ./backend/docker-compose.yml build --no-cache 
          docker compose -f ./backend/docker-compose.yml push

      - name: Upload Docker Compose file for deployment
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-backend-file
          path: ./backend/docker-compose.yml
