name: Build and deploy images to Docker Hub
on:
  push:
    branches:
      - 284-implementa-cicd-da-disciplina-de-testes-no-github-actions
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-teste:latest -f backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-teste:latest
      - name: Upload Docker Compose file for deployment
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-file
          path: docker-compose.yml
