name: React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend/v2/

      - name: Build the project
        run: yarn build
        working-directory: ./frontend/v2/
