# Generated by Django 4.2.6 on 2023-10-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='bairro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='bio',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone2',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
