# Generated by Django 4.2.6 on 2023-10-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0002_alter_colaborador_bairro_alter_colaborador_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador_acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convite', models.CharField(choices=[('ESP', 'Em espera'), ('ACC', 'Aceito'), ('REJ', 'Rejeitado'), ('PART', 'Participou')], max_length=4, null=True)),
                ('data_convite', models.DateTimeField(null=True)),
                ('solicitacao', models.CharField(choices=[('ESP', 'Em espera'), ('ACC', 'Aceito'), ('REJ', 'Rejeitado'), ('PART', 'Participou')], max_length=4, null=True)),
                ('data_solicitacao', models.DateTimeField(null=True)),
                ('responsavel', models.BooleanField(null=True)),
                ('data_responsavel', models.DateTimeField(null=True)),
                ('criador', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('colaborador_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.colaborador_acao')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ManyToManyField(blank=True, to='APIQAjuda.categoria')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.colaborador')),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='Responsavel',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='voluntario',
        ),
        migrations.AlterField(
            model_name='acao',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIQAjuda.colaborador'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='local',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='acao',
            name='tema',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
        migrations.AddField(
            model_name='colaborador_acao',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.acao'),
        ),
        migrations.AddField(
            model_name='colaborador_acao',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.colaborador'),
        ),
    ]
