# Generated by Django 4.2.6 on 2023-10-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0006_alter_acao_categoria_alter_acao_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador_acao',
            name='data_convite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
