# Generated by Django 4.2.6 on 2023-10-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0007_alter_colaborador_acao_data_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador_acao',
            name='convite',
            field=models.CharField(blank=True, choices=[('E', 'Em espera'), ('A', 'Aceito'), ('R', 'Rejeitado'), ('P', 'Participou')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador_acao',
            name='solicitacao',
            field=models.CharField(blank=True, choices=[('E', 'Em espera'), ('A', 'Aceito'), ('R', 'Rejeitado'), ('P', 'Participou')], max_length=1, null=True),
        ),
    ]
