# Generated by Django 4.2.6 on 2023-10-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0011_remove_colaborador_acao_criador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferencia',
        ),
    ]
