# Generated by Django 4.2.6 on 2023-12-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0013_remove_foto_acao_acao_foto_foto_nome_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='foto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.foto'),
        ),
    ]
