# Generated by Django 4.2.6 on 2023-12-14 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0019_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='foto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APIQAjuda.foto'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(default='limpeza-praia.jpg', upload_to='media'),
        ),
    ]
