# Generated by Django 4.2.6 on 2023-12-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0022_remove_acao_criador_acao_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='qtd_volunt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
