# Generated by Django 4.2.6 on 2023-12-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIQAjuda', '0023_acao_qtd_volunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='qtd_volunt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
